backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: 标题, name: title, widget: string}
      - {label: 描述, name: description, widget: text, required: false}
      - {label: Date, name: date, widget: datetime}
      - {label: Body, name: body, widget: markdown}
